Added Translations for Punjabi Language
amahi/android pull request #684
Opened 2020-11-03 21:20 UTC by shivamsawlani02

@chirag-jn 
I have added Punjabi Language. Please review these changes.

#548

2020-11-05 12:55 UTC, chirag-jn requested changes

2020-11-05 12:55 UTC, chirag-jn commented on src/main/res/values-pa/strings.xml
> +    <string name="message_error_amahi_anywhere_app">Amahi Anywhere ਤੁਹਾਡੇ ਸਰਵਰ ਵਿੱਚ ਐਪ ਪਹੁੰਚਯੋਗ ਨਹੀਂ ਹੈ. ਕਿਰਪਾ ਕਰਕੇ ਇਹ ਸੁਨਿਸ਼ਚਿਤ ਕਰੋ ਕਿ ਤੁਹਾਡੇ ਨੈਟਵਰਕ ਵਿੱਚ Amahi Anywhere ਐਪ ਸਥਾਪਿਤ, ਚੱਲ ਰਹੀ ਅਤੇ ਪਹੁੰਚਯ
English inside a string. We are translating Amahi at other places too. Please correct this.

2020-11-05 12:55 UTC, chirag-jn commented on src/main/res/values-pa/strings.xml
> +    <string name="title_version_settings">ਐਂਡਰਾਇਡ ਲਈ Amahi</string>
English inside a string.

2020-11-05 14:40 UTC, chirag-jn commented
Please add copyright to `values-pa/strings.xml`. Refer `values/strings.xml` for the format and text.

2020-11-05 19:45 UTC, shivamsawlani02 commented
Ok.I will make these changes

2020-11-05 20:38 UTC, shivamsawlani02 commented
@chirag-jn I have made the required changes. Please review them.

2020-12-24 11:02 UTC, shivamsawlani02 commented
Hey @chirag-jn ! Can you please review this pull request and tell me changes(if any)?

2020-12-28 18:27 UTC, Prakhar-Agarwal-byte reviewed
@shivamsawlani02 Your branch has conflicts with Amahi: beta branch, please resolve them.

2020-12-28 19:25 UTC, chirag-jn commented
Please rebase the branch so that the merge conflicts are resolved.

2020-12-30 19:27 UTC, shivamsawlani02 commented
@chirag-jn  I have resolved the merge conflicts. Please have a look now.

2020-12-31 13:05 UTC, chirag-jn commented
@shivamsawlani02 did you try it locally? Build should have failed locally in my opinion.

2020-12-31 13:06 UTC, chirag-jn requested changes

2020-12-31 13:06 UTC, chirag-jn commented on src/main/res/values-te/strings.xml
>      <string name="language_te">తెలుగు</string>
`language_te` present twice.

2021-01-01 10:43 UTC, shivamsawlani02 commented
> @shivamsawlani02 did you try it locally? Build should have failed locally in my opinion.

Yes I did that locally.

2021-01-01 10:44 UTC, shivamsawlani02 commented on src/main/res/values-te/strings.xml
>      <string name="language_te">తెలుగు</string>
Resolved.

2021-02-27 17:18 UTC, merged