Grammar correction
amahi/android pull request #690
Opened 2020-11-04 20:53 UTC by Prakhar-Agarwal-byte

@chirag-jn @cpg Kindly review my Pull Request and merge.

2020-11-04 23:58 UTC, cpg commented on src/main/res/values/strings.xml
> +    <string name="sort_by">Sort bfy</string>
typo. please correct.

2020-11-05 06:01 UTC, Prakhar-Agarwal-byte commented on src/main/res/values/strings.xml
> +    <string name="sort_by">Sort bfy</string>
Okay on it.

2020-11-05 06:04 UTC, Prakhar-Agarwal-byte commented on src/main/res/values/strings.xml
> +    <string name="sort_by">Sort bfy</string>
@cpg corrected the typo.

2020-11-05 09:54 UTC, Prakhar-Agarwal-byte commented
I have corrected the typo. Please merge

2020-11-05 13:49 UTC, chirag-jn commented
I have left some comments. Please check the same. Also shouldn't it be `de` instead of `gem` in values folder name and string variables?
Ref: https://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android

2020-11-05 14:35 UTC, chirag-jn requested changes

2020-11-05 14:35 UTC, chirag-jn commented on src/main/res/values/strings.xml
> +    <string name="preference_summary_server">Select server</string>
Please follow either sentence case for all sentences or capitalization of the first letter of each word but please don't use both strategies.

2020-11-06 13:32 UTC, prakharagarwal-dev commented on src/main/res/values/strings.xml
> +    <string name="preference_summary_server">Select server</string>
Yes, you are correct, I missed it.
Actually what I was trying to do was to capitalize the first letter of each word which is a title except prepositions and use sentence case for all sentences.
Please tell me what to which one to proceed with.

2020-11-06 13:32 UTC, prakharagarwal-dev commented on src/main/res/values/strings.xml
> +    <string name="preference_summary_server">Select server</string>
I have made some changes according to your review. Please review them.

2020-12-04 21:10 UTC, merged